### ISSUE TITLE
create google forms for feedback for every chapter and/or section

### ISSUE THREAD

**Issue by fouticus** [CSU-R/Module1#11]
I think we can provide a single google form and have students indicate which section they're providing feedback on.

I suggest making this part of a "progress check"

possible questions:

1. How confident are you in the concepts explained in this section/chapter?
2. Which specific concepts were confusing to you?
3. Do you think there was (too little, enough, too much) progress checks?
4. What errors, if any, did you find the book?

Need to:
- [x] Make the google form
- [x] embed the link at the end of the chapters (or sections, if we decide that)

**Comment by lizita** [comment]
I made a form and changed the permissions to anyone can edit: https://docs.google.com/forms/d/1ueTgp2dBaVvcVvpG3Fz_6jVCguk78BYcKf2dYX5Qaxo/edit?usp=sharing

As long as you have edit rights you can see the responses - but I wonder if I can hand off the form to Matt so he can be the "owner" and I won't be linked to it anymore?

It will make a new link to put in the book for students to give feedback. 

What do you think? I think it would be best to put it at the end of sections, since some are pretty lengthy. I made the section question short answer but it could also be drop down if that would make organizing the responses easier.

**Comment by fouticus** [comment]
I like the simplicity, so it's not a huge burden, especially because students will be asked several times to fill it out. We can revisit questions later, but I'm wondering if email/section are not required. Maybe there's a "anything else you'd like to tell us?" box, where someone could give their contact info if they want. 

If students are taking the CSU course, they can contact the instructor through canvas anyways if they need support. 

Probably long term, Matt or I can be owners. We'll want to have all drive files in one shared folder probably. This repo is public, so I'd hate for someone to find the link and mess with it. I'll share drive folder with you.

**Comment by lizita** [comment]
Yeah, "collect email addresses" is a box that I checked but we can uncheck it. I'll change the permission to private, but I think I can move it to the common drive folder and allow just y'all edit rights. It would be cool if the url can stay the same, but if not I can update it.

**Comment by fouticus** [comment]
@lizita were you able to move the google form to the shared drive?

**Comment by fouticus** [comment]
Got it, thanks. Only thing left is to update the book chapter/section dropdown. I'd rather students pick from a list than have to type it in. 

We can do this after the book is more solid.

**Comment by fouticus** [comment]
Actually, I just left the section question as a short answer, but created pre-filled links so when students click on a particular feedback block the section question gets filled in automatically. see (6693f2a2c82f9d4d32ab9aad3a595ba3987ef3ed)

**Comment by fouticus** [comment]
There's an r script under /rscripts which generates the feedback blocks for each section. You can add a new section to the list and run the script, which will print out the block for each location, each with a different pre-filled link.
