### ISSUE TITLE
Fix inline code color in bonus blocks.

### ISSUE THREAD

**Issue by fouticus** [CSU-R/Module1#3]
Fix inline code color in bonus blocks. Text is white, and background of inline code is very light, so you can't read the text. 

See here:

https://stackoverflow.com/questions/50727217/rmarkdown-change-inline-code-color

**Comment by fouticus** [comment]
example:

![image](https://user-images.githubusercontent.com/10353313/85950491-4409c280-b91a-11ea-93a5-08bc2109bb55.png)

**Comment by lizita** [comment]
I changed the color with the [html span thing](https://stackoverflow.com/questions/29067541/how-to-change-the-font-color), but it also makes the original bookdown code harder to read. Could be worth considering changing the block color if that weighs in to the project. 

<img width="772" alt="Screen Shot 2020-07-02 at 17 18 57" src="https://user-images.githubusercontent.com/34800219/86413919-288b1880-bc88-11ea-810f-22ff4336bc2d.png">

**Comment by fouticus** [comment]
#15

**Comment by fouticus** [comment]
Yeah, changing the bonus block color might be the easier thing to do. Let's use your solution for now, then revisit later if we need to.

**Comment by fouticus** [comment]
Bonus blocks are now a different color, and all text is black, also, found a way to edit the background color of inline code globally using css styles and by editing the LaTeX verbatim environment. 
Final commit was: 2335e37db9187f6d83f6c657cbfdbd7b2afd8ae5

**Comment by lizita** [comment]
The boxes look good! I think I prefer them without borders and might pick some different colors, but I'll leave those aesthetic decisions to y'all. It is still a little hard to tell it's inline code since the background is just a darker shade of the box color - I think would be better if it was lighter or the standard grey shade. 

<img width="432" alt="Screen Shot 2020-07-08 at 07 35 58" src="https://user-images.githubusercontent.com/34800219/86925417-1a0c8900-c0ee-11ea-82f2-153e6e3c5ec4.png">

**Comment by fouticus** [comment]
Thanks! I'm certainly no graphic designer, so I'm sure the aesthetics could be better. I think we could change the CSS to lighten the code background instead of darkening it, but I think that would make the code outside of the boxes just have a white background, which wouldn't differentiate it from the surrounding text. Having a constant color could work, but it just looked a bit jarring to my eye to have grey against a colored box background. This might be a matter of taste.

**Comment by fouticus** [comment]
Given that the class starts next week, I'll be focusing on other issues for the time being.
