### ISSUE TITLE
Change color of code chunks and output

### ISSUE THREAD

**Issue by fouticus** [CSU-R/Module1#4]
It would be nice if there were some background shading for code chunks and output to distinguish them. I've added styles to style.css and set them as the default styles for code chunks in index.Rmd, but it's not working as advertised (I believe). Needs some debugging. 

See:
https://bookdown.org/yihui/rmarkdown-cookbook/chunk-styling.html

**Comment by matthewross07** [comment]
After fiddling for an hour, even the default bootstrap.css backgrounds don't work like "bg.danger". I have no clue why this would be the case. I'll test on my work computer next week,

matt

**Comment by fouticus** [comment]
I found out that using gitbook disables using any bootstrap themes. I haven't been able to override the gibook themes yet, but still working.

**Comment by matthewross07** [comment]
Oh interesting. Maybe we can just use a different base theme? 

https://bookdown.org/yihui/bookdown/theming.html

html_book?

**Comment by fouticus** [comment]
I thought about that, but the side navigation of gitbook might be hard to replicate. My estimate is that I can figure out how to work with gitbook faster than I could recreate the nice things from gitbook.

**Comment by fouticus** [comment]
Fixed with commit: 8c8295414a9a299e2084b6b8f82cf0e3f7a30bda
